title: Verónika Troitskaia
timezone: Europe/Lisbon

author:
  name: Verónika Troitskaia
  url: https://www.veronika.pt

#logo: /assets/img/logo.png
description: Discover the latest rental market trends in Lisbon with expert insights and practical tips. Learn about pricing, demand, top neighborhoods, and essential advice for tenants and landlords in Portugal’s capital.

url: https://blog.veronika.pt
permalink: /:title

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
  - scope:
      path: ""
      type: posts
    values:
      layout: post

plugins:
  - jekyll-seo-tag
