title: Verónika Troitskaia
timezone: Europe/Lisbon
lang: en

author:
  name: Verónika Troitskaia
  url: https://www.veronika.pt

#logo: /assets/img/logo.png
description: The Ultimate Guide to Real Estate in Lisbon – Rental Market Trends, Tips, and Insights.
long_description: Discover the latest rental market trends in Lisbon with expert insights and practical tips. Learn about pricing, demand, top neighborhoods, and essential advice for tenants and landlords in Portugal’s capital.

url: https://blog.veronika.pt
permalink: /:title

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
  - scope:
      path: ""
      type: posts
    values:
      layout: post

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
